// Code generated by the Encore 1.48.13 client generator. DO NOT EDIT.

// Disable eslint, jshint, and jslint for this file.
/* eslint-disable */
/* jshint ignore:start */
/*jslint-disable*/
import type { CookieWithOptions } from "encore.dev/api";

/**
 * BaseURL is the base URL for calling the Encore application's API.
 */
export type BaseURL = string

export const Local: BaseURL = "http://localhost:4000"

/**
 * Environment returns a BaseURL for calling the cloud environment with the given name.
 */
export function Environment(name: string): BaseURL {
    return `https://${name}-.encr.app`
}

/**
 * PreviewEnv returns a BaseURL for calling the preview environment with the given PR number.
 */
export function PreviewEnv(pr: number | string): BaseURL {
    return Environment(`pr${pr}`)
}

const BROWSER = typeof globalThis === "object" && ("window" in globalThis);

/**
 * Client is an API client for the  Encore application.
 */
export class Client {
    public readonly admin: admin.ServiceClient
    public readonly analytics: analytics.ServiceClient
    public readonly clinic: clinic.ServiceClient
    public readonly reviews: reviews.ServiceClient
    public readonly stripe: stripe.ServiceClient
    public readonly supabase: supabase.ServiceClient
    public readonly telemedicine: telemedicine.ServiceClient
    private readonly options: ClientOptions
    private readonly target: string


    /**
     * Creates a Client for calling the public and authenticated APIs of your Encore application.
     *
     * @param target  The target which the client should be configured to use. See Local and Environment for options.
     * @param options Options for the client
     */
    constructor(target: BaseURL, options?: ClientOptions) {
        this.target = target
        this.options = options ?? {}
        const base = new BaseClient(this.target, this.options)
        this.admin = new admin.ServiceClient(base)
        this.analytics = new analytics.ServiceClient(base)
        this.clinic = new clinic.ServiceClient(base)
        this.reviews = new reviews.ServiceClient(base)
        this.stripe = new stripe.ServiceClient(base)
        this.supabase = new supabase.ServiceClient(base)
        this.telemedicine = new telemedicine.ServiceClient(base)
    }

    /**
     * Creates a new Encore client with the given client options set.
     *
     * @param options Client options to set. They are merged with existing options.
     **/
    public with(options: ClientOptions): Client {
        return new Client(this.target, {
            ...this.options,
            ...options,
        })
    }
}

/**
 * Import the auth handler to be able to derive the auth type
 */
import type { supabaseAuth as auth_supabaseAuth } from "~backend/supabase/auth";

/**
 * ClientOptions allows you to override any default behaviour within the generated Encore client.
 */
export interface ClientOptions {
    /**
     * By default the client will use the inbuilt fetch function for making the API requests.
     * however you can override it with your own implementation here if you want to run custom
     * code on each API request made or response received.
     */
    fetcher?: Fetcher

    /** Default RequestInit to be used for the client */
    requestInit?: Omit<RequestInit, "headers"> & { headers?: Record<string, string> }

    /**
     * Allows you to set the authentication data to be used for each
     * request either by passing in a static object or by passing in
     * a function which returns a new object for each request.
     */
    auth?: RequestType<typeof auth_supabaseAuth> | AuthDataGenerator
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import {
    createSubAdmin as api_admin_sub_admin_createSubAdmin,
    getUserPermissions as api_admin_sub_admin_getUserPermissions,
    listDepartments as api_admin_sub_admin_listDepartments,
    listSubAdmins as api_admin_sub_admin_listSubAdmins,
    updateSubAdminPermissions as api_admin_sub_admin_updateSubAdminPermissions
} from "~backend/admin/sub_admin";

export namespace admin {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.createSubAdmin = this.createSubAdmin.bind(this)
            this.getUserPermissions = this.getUserPermissions.bind(this)
            this.listDepartments = this.listDepartments.bind(this)
            this.listSubAdmins = this.listSubAdmins.bind(this)
            this.updateSubAdminPermissions = this.updateSubAdminPermissions.bind(this)
        }

        /**
         * Creates a new sub-admin user with permissions
         */
        public async createSubAdmin(params: RequestType<typeof api_admin_sub_admin_createSubAdmin>): Promise<ResponseType<typeof api_admin_sub_admin_createSubAdmin>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/admin/sub-admins`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_admin_sub_admin_createSubAdmin>
        }

        /**
         * Gets permissions for the current user
         */
        public async getUserPermissions(): Promise<ResponseType<typeof api_admin_sub_admin_getUserPermissions>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/admin/my-permissions`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_admin_sub_admin_getUserPermissions>
        }

        /**
         * Lists all departments
         */
        public async listDepartments(): Promise<ResponseType<typeof api_admin_sub_admin_listDepartments>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/admin/departments`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_admin_sub_admin_listDepartments>
        }

        /**
         * Lists all sub-admin users
         */
        public async listSubAdmins(): Promise<ResponseType<typeof api_admin_sub_admin_listSubAdmins>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/admin/sub-admins`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_admin_sub_admin_listSubAdmins>
        }

        /**
         * Updates sub-admin permissions
         */
        public async updateSubAdminPermissions(params: RequestType<typeof api_admin_sub_admin_updateSubAdminPermissions>): Promise<ResponseType<typeof api_admin_sub_admin_updateSubAdminPermissions>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/admin/sub-admin-permissions`, {method: "PUT", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_admin_sub_admin_updateSubAdminPermissions>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import {
    getAppointmentTrends as api_analytics_dashboard_getAppointmentTrends,
    getDashboardStats as api_analytics_dashboard_getDashboardStats,
    getDoctorPerformance as api_analytics_dashboard_getDoctorPerformance,
    getRevenueTrends as api_analytics_dashboard_getRevenueTrends
} from "~backend/analytics/dashboard";

export namespace analytics {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.getAppointmentTrends = this.getAppointmentTrends.bind(this)
            this.getDashboardStats = this.getDashboardStats.bind(this)
            this.getDoctorPerformance = this.getDoctorPerformance.bind(this)
            this.getRevenueTrends = this.getRevenueTrends.bind(this)
        }

        /**
         * Retrieves appointment trends.
         */
        public async getAppointmentTrends(params: RequestType<typeof api_analytics_dashboard_getAppointmentTrends>): Promise<ResponseType<typeof api_analytics_dashboard_getAppointmentTrends>> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                period: String(params.period),
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/analytics/appointment-trends`, {query, method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_analytics_dashboard_getAppointmentTrends>
        }

        /**
         * Retrieves dashboard statistics.
         */
        public async getDashboardStats(): Promise<ResponseType<typeof api_analytics_dashboard_getDashboardStats>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/analytics/dashboard`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_analytics_dashboard_getDashboardStats>
        }

        /**
         * Retrieves doctor performance metrics.
         */
        public async getDoctorPerformance(): Promise<ResponseType<typeof api_analytics_dashboard_getDoctorPerformance>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/analytics/doctor-performance`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_analytics_dashboard_getDoctorPerformance>
        }

        /**
         * Retrieves revenue trends.
         */
        public async getRevenueTrends(params: RequestType<typeof api_analytics_dashboard_getRevenueTrends>): Promise<ResponseType<typeof api_analytics_dashboard_getRevenueTrends>> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                period: String(params.period),
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/analytics/revenue-trends`, {query, method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_analytics_dashboard_getRevenueTrends>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import {
    createAppointment as api_clinic_appointment_createAppointment,
    deleteAppointment as api_clinic_appointment_deleteAppointment,
    getAppointment as api_clinic_appointment_getAppointment,
    listAppointments as api_clinic_appointment_listAppointments,
    updateAppointment as api_clinic_appointment_updateAppointment
} from "~backend/clinic/appointment";
import {
    createBill as api_clinic_billing_createBill,
    deleteBill as api_clinic_billing_deleteBill,
    getBill as api_clinic_billing_getBill,
    listBills as api_clinic_billing_listBills,
    updateBill as api_clinic_billing_updateBill
} from "~backend/clinic/billing";
import {
    createDoctor as api_clinic_doctor_createDoctor,
    deleteDoctor as api_clinic_doctor_deleteDoctor,
    getDoctor as api_clinic_doctor_getDoctor,
    listDoctors as api_clinic_doctor_listDoctors,
    updateDoctor as api_clinic_doctor_updateDoctor
} from "~backend/clinic/doctor";
import { getLabReportUploadUrl as api_clinic_fileUpload_getLabReportUploadUrl } from "~backend/clinic/fileUpload";
import {
    createPatient as api_clinic_patient_createPatient,
    deletePatient as api_clinic_patient_deletePatient,
    getPatient as api_clinic_patient_getPatient,
    listPatients as api_clinic_patient_listPatients,
    updatePatient as api_clinic_patient_updatePatient
} from "~backend/clinic/patient";
import {
    createPrescription as api_clinic_prescription_createPrescription,
    deletePrescription as api_clinic_prescription_deletePrescription,
    getPrescription as api_clinic_prescription_getPrescription,
    listPrescriptions as api_clinic_prescription_listPrescriptions,
    updatePrescription as api_clinic_prescription_updatePrescription
} from "~backend/clinic/prescription";

export namespace clinic {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.createAppointment = this.createAppointment.bind(this)
            this.createBill = this.createBill.bind(this)
            this.createDoctor = this.createDoctor.bind(this)
            this.createPatient = this.createPatient.bind(this)
            this.createPrescription = this.createPrescription.bind(this)
            this.deleteAppointment = this.deleteAppointment.bind(this)
            this.deleteBill = this.deleteBill.bind(this)
            this.deleteDoctor = this.deleteDoctor.bind(this)
            this.deletePatient = this.deletePatient.bind(this)
            this.deletePrescription = this.deletePrescription.bind(this)
            this.getAppointment = this.getAppointment.bind(this)
            this.getBill = this.getBill.bind(this)
            this.getDoctor = this.getDoctor.bind(this)
            this.getLabReportUploadUrl = this.getLabReportUploadUrl.bind(this)
            this.getPatient = this.getPatient.bind(this)
            this.getPrescription = this.getPrescription.bind(this)
            this.listAppointments = this.listAppointments.bind(this)
            this.listBills = this.listBills.bind(this)
            this.listDoctors = this.listDoctors.bind(this)
            this.listPatients = this.listPatients.bind(this)
            this.listPrescriptions = this.listPrescriptions.bind(this)
            this.updateAppointment = this.updateAppointment.bind(this)
            this.updateBill = this.updateBill.bind(this)
            this.updateDoctor = this.updateDoctor.bind(this)
            this.updatePatient = this.updatePatient.bind(this)
            this.updatePrescription = this.updatePrescription.bind(this)
        }

        /**
         * Creates a new appointment.
         */
        public async createAppointment(params: RequestType<typeof api_clinic_appointment_createAppointment>): Promise<ResponseType<typeof api_clinic_appointment_createAppointment>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/appointments`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_clinic_appointment_createAppointment>
        }

        /**
         * Creates a new bill.
         */
        public async createBill(params: RequestType<typeof api_clinic_billing_createBill>): Promise<ResponseType<typeof api_clinic_billing_createBill>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/bills`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_clinic_billing_createBill>
        }

        /**
         * Creates a new doctor record.
         */
        public async createDoctor(params: RequestType<typeof api_clinic_doctor_createDoctor>): Promise<ResponseType<typeof api_clinic_doctor_createDoctor>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/doctors`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_clinic_doctor_createDoctor>
        }

        /**
         * Creates a new patient record.
         */
        public async createPatient(params: RequestType<typeof api_clinic_patient_createPatient>): Promise<ResponseType<typeof api_clinic_patient_createPatient>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/patients`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_clinic_patient_createPatient>
        }

        /**
         * Creates a new prescription.
         */
        public async createPrescription(params: RequestType<typeof api_clinic_prescription_createPrescription>): Promise<ResponseType<typeof api_clinic_prescription_createPrescription>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/prescriptions`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_clinic_prescription_createPrescription>
        }

        /**
         * Deletes an appointment.
         */
        public async deleteAppointment(params: { id: string }): Promise<void> {
            await this.baseClient.callTypedAPI(`/appointments/${encodeURIComponent(params.id)}`, {method: "DELETE", body: undefined})
        }

        /**
         * Deletes a bill.
         */
        public async deleteBill(params: { id: string }): Promise<void> {
            await this.baseClient.callTypedAPI(`/bills/${encodeURIComponent(params.id)}`, {method: "DELETE", body: undefined})
        }

        /**
         * Deletes a doctor record.
         */
        public async deleteDoctor(params: { id: string }): Promise<void> {
            await this.baseClient.callTypedAPI(`/doctors/${encodeURIComponent(params.id)}`, {method: "DELETE", body: undefined})
        }

        /**
         * Deletes a patient record.
         */
        public async deletePatient(params: { id: string }): Promise<void> {
            await this.baseClient.callTypedAPI(`/patients/${encodeURIComponent(params.id)}`, {method: "DELETE", body: undefined})
        }

        /**
         * Deletes a prescription.
         */
        public async deletePrescription(params: { id: string }): Promise<void> {
            await this.baseClient.callTypedAPI(`/prescriptions/${encodeURIComponent(params.id)}`, {method: "DELETE", body: undefined})
        }

        /**
         * Retrieves an appointment by ID.
         */
        public async getAppointment(params: { id: string }): Promise<ResponseType<typeof api_clinic_appointment_getAppointment>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/appointments/${encodeURIComponent(params.id)}`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_clinic_appointment_getAppointment>
        }

        /**
         * Retrieves a bill by ID.
         */
        public async getBill(params: { id: string }): Promise<ResponseType<typeof api_clinic_billing_getBill>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/bills/${encodeURIComponent(params.id)}`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_clinic_billing_getBill>
        }

        /**
         * Retrieves a doctor by ID.
         */
        public async getDoctor(params: { id: string }): Promise<ResponseType<typeof api_clinic_doctor_getDoctor>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/doctors/${encodeURIComponent(params.id)}`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_clinic_doctor_getDoctor>
        }

        /**
         * Generates a signed URL for uploading a lab report.
         */
        public async getLabReportUploadUrl(params: RequestType<typeof api_clinic_fileUpload_getLabReportUploadUrl>): Promise<ResponseType<typeof api_clinic_fileUpload_getLabReportUploadUrl>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/files/lab-report/upload-url`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_clinic_fileUpload_getLabReportUploadUrl>
        }

        /**
         * Retrieves a patient by ID.
         */
        public async getPatient(params: { id: string }): Promise<ResponseType<typeof api_clinic_patient_getPatient>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/patients/${encodeURIComponent(params.id)}`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_clinic_patient_getPatient>
        }

        /**
         * Retrieves a prescription by ID.
         */
        public async getPrescription(params: { id: string }): Promise<ResponseType<typeof api_clinic_prescription_getPrescription>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/prescriptions/${encodeURIComponent(params.id)}`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_clinic_prescription_getPrescription>
        }

        /**
         * Lists appointments with optional filtering.
         */
        public async listAppointments(params: RequestType<typeof api_clinic_appointment_listAppointments>): Promise<ResponseType<typeof api_clinic_appointment_listAppointments>> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                date:      params.date === undefined ? undefined : params.date.toISOString(),
                doctorId:  params.doctorId,
                limit:     params.limit === undefined ? undefined : String(params.limit),
                offset:    params.offset === undefined ? undefined : String(params.offset),
                patientId: params.patientId,
                status:    params.status,
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/appointments`, {query, method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_clinic_appointment_listAppointments>
        }

        /**
         * Lists bills with optional filtering.
         */
        public async listBills(params: RequestType<typeof api_clinic_billing_listBills>): Promise<ResponseType<typeof api_clinic_billing_listBills>> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                appointmentId: params.appointmentId,
                limit:         params.limit === undefined ? undefined : String(params.limit),
                offset:        params.offset === undefined ? undefined : String(params.offset),
                patientId:     params.patientId,
                status:        params.status,
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/bills`, {query, method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_clinic_billing_listBills>
        }

        /**
         * Lists all doctors with optional filtering.
         */
        public async listDoctors(params: RequestType<typeof api_clinic_doctor_listDoctors>): Promise<ResponseType<typeof api_clinic_doctor_listDoctors>> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                limit:          params.limit === undefined ? undefined : String(params.limit),
                offset:         params.offset === undefined ? undefined : String(params.offset),
                search:         params.search,
                specialization: params.specialization,
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/doctors`, {query, method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_clinic_doctor_listDoctors>
        }

        /**
         * Lists all patients with optional search and pagination.
         */
        public async listPatients(params: RequestType<typeof api_clinic_patient_listPatients>): Promise<ResponseType<typeof api_clinic_patient_listPatients>> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                limit:  params.limit === undefined ? undefined : String(params.limit),
                offset: params.offset === undefined ? undefined : String(params.offset),
                search: params.search,
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/patients`, {query, method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_clinic_patient_listPatients>
        }

        /**
         * Lists prescriptions with optional filtering.
         */
        public async listPrescriptions(params: RequestType<typeof api_clinic_prescription_listPrescriptions>): Promise<ResponseType<typeof api_clinic_prescription_listPrescriptions>> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                appointmentId: params.appointmentId,
                doctorId:      params.doctorId,
                limit:         params.limit === undefined ? undefined : String(params.limit),
                offset:        params.offset === undefined ? undefined : String(params.offset),
                patientId:     params.patientId,
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/prescriptions`, {query, method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_clinic_prescription_listPrescriptions>
        }

        /**
         * Updates an existing appointment.
         */
        public async updateAppointment(params: RequestType<typeof api_clinic_appointment_updateAppointment>): Promise<ResponseType<typeof api_clinic_appointment_updateAppointment>> {
            // Construct the body with only the fields which we want encoded within the body (excluding query string or header fields)
            const body: Record<string, any> = {
                appointmentDate: params.appointmentDate,
                diagnosis:       params.diagnosis,
                duration:        params.duration,
                notes:           params.notes,
                prescription:    params.prescription,
                status:          params.status,
                symptoms:        params.symptoms,
                type:            params.type,
            }

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/appointments/${encodeURIComponent(params.id)}`, {method: "PUT", body: JSON.stringify(body)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_clinic_appointment_updateAppointment>
        }

        /**
         * Updates an existing bill.
         */
        public async updateBill(params: RequestType<typeof api_clinic_billing_updateBill>): Promise<ResponseType<typeof api_clinic_billing_updateBill>> {
            // Construct the body with only the fields which we want encoded within the body (excluding query string or header fields)
            const body: Record<string, any> = {
                amount:           params.amount,
                dueDate:          params.dueDate,
                paidAt:           params.paidAt,
                paymentMethod:    params.paymentMethod,
                paymentReference: params.paymentReference,
                status:           params.status,
                taxAmount:        params.taxAmount,
            }

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/bills/${encodeURIComponent(params.id)}`, {method: "PUT", body: JSON.stringify(body)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_clinic_billing_updateBill>
        }

        /**
         * Updates an existing doctor record.
         */
        public async updateDoctor(params: RequestType<typeof api_clinic_doctor_updateDoctor>): Promise<ResponseType<typeof api_clinic_doctor_updateDoctor>> {
            // Construct the body with only the fields which we want encoded within the body (excluding query string or header fields)
            const body: Record<string, any> = {
                availability:    params.availability,
                bio:             params.bio,
                consultationFee: params.consultationFee,
                email:           params.email,
                experience:      params.experience,
                firstName:       params.firstName,
                lastName:        params.lastName,
                licenseNumber:   params.licenseNumber,
                phone:           params.phone,
                profileImage:    params.profileImage,
                qualification:   params.qualification,
                specialization:  params.specialization,
            }

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/doctors/${encodeURIComponent(params.id)}`, {method: "PUT", body: JSON.stringify(body)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_clinic_doctor_updateDoctor>
        }

        /**
         * Updates an existing patient record.
         */
        public async updatePatient(params: RequestType<typeof api_clinic_patient_updatePatient>): Promise<ResponseType<typeof api_clinic_patient_updatePatient>> {
            // Construct the body with only the fields which we want encoded within the body (excluding query string or header fields)
            const body: Record<string, any> = {
                address:            params.address,
                allergies:          params.allergies,
                currentMedications: params.currentMedications,
                dateOfBirth:        params.dateOfBirth,
                email:              params.email,
                emergencyContact:   params.emergencyContact,
                emergencyPhone:     params.emergencyPhone,
                firstName:          params.firstName,
                gender:             params.gender,
                lastName:           params.lastName,
                medicalHistory:     params.medicalHistory,
                phone:              params.phone,
            }

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/patients/${encodeURIComponent(params.id)}`, {method: "PUT", body: JSON.stringify(body)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_clinic_patient_updatePatient>
        }

        /**
         * Updates an existing prescription.
         */
        public async updatePrescription(params: RequestType<typeof api_clinic_prescription_updatePrescription>): Promise<ResponseType<typeof api_clinic_prescription_updatePrescription>> {
            // Construct the body with only the fields which we want encoded within the body (excluding query string or header fields)
            const body: Record<string, any> = {
                dosage:         params.dosage,
                duration:       params.duration,
                frequency:      params.frequency,
                instructions:   params.instructions,
                medicationName: params.medicationName,
            }

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/prescriptions/${encodeURIComponent(params.id)}`, {method: "PUT", body: JSON.stringify(body)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_clinic_prescription_updatePrescription>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import {
    canReviewAppointment as api_reviews_review_canReviewAppointment,
    createReview as api_reviews_review_createReview,
    deleteReview as api_reviews_review_deleteReview,
    getReview as api_reviews_review_getReview,
    getReviewStats as api_reviews_review_getReviewStats,
    listReviews as api_reviews_review_listReviews,
    updateReview as api_reviews_review_updateReview
} from "~backend/reviews/review";

export namespace reviews {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.canReviewAppointment = this.canReviewAppointment.bind(this)
            this.createReview = this.createReview.bind(this)
            this.deleteReview = this.deleteReview.bind(this)
            this.getReview = this.getReview.bind(this)
            this.getReviewStats = this.getReviewStats.bind(this)
            this.listReviews = this.listReviews.bind(this)
            this.updateReview = this.updateReview.bind(this)
        }

        /**
         * Checks if a patient can review an appointment
         */
        public async canReviewAppointment(params: { appointmentId: string }): Promise<ResponseType<typeof api_reviews_review_canReviewAppointment>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/reviews/can-review/${encodeURIComponent(params.appointmentId)}`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_reviews_review_canReviewAppointment>
        }

        /**
         * Creates a new review
         */
        public async createReview(params: RequestType<typeof api_reviews_review_createReview>): Promise<ResponseType<typeof api_reviews_review_createReview>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/reviews`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_reviews_review_createReview>
        }

        /**
         * Deletes a review
         */
        public async deleteReview(params: { id: string }): Promise<void> {
            await this.baseClient.callTypedAPI(`/reviews/${encodeURIComponent(params.id)}`, {method: "DELETE", body: undefined})
        }

        /**
         * Retrieves a review by ID
         */
        public async getReview(params: { id: string }): Promise<ResponseType<typeof api_reviews_review_getReview>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/reviews/${encodeURIComponent(params.id)}`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_reviews_review_getReview>
        }

        /**
         * Gets review statistics
         */
        public async getReviewStats(params: RequestType<typeof api_reviews_review_getReviewStats>): Promise<ResponseType<typeof api_reviews_review_getReviewStats>> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                doctorId:  params.doctorId,
                endDate:   params.endDate === undefined ? undefined : params.endDate.toISOString(),
                startDate: params.startDate === undefined ? undefined : params.startDate.toISOString(),
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/reviews/stats`, {query, method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_reviews_review_getReviewStats>
        }

        /**
         * Lists reviews with optional filtering
         */
        public async listReviews(params: RequestType<typeof api_reviews_review_listReviews>): Promise<ResponseType<typeof api_reviews_review_listReviews>> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                appointmentId: params.appointmentId,
                doctorId:      params.doctorId,
                isApproved:    params.isApproved === undefined ? undefined : String(params.isApproved),
                limit:         params.limit === undefined ? undefined : String(params.limit),
                minRating:     params.minRating === undefined ? undefined : String(params.minRating),
                offset:        params.offset === undefined ? undefined : String(params.offset),
                patientId:     params.patientId,
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/reviews`, {query, method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_reviews_review_listReviews>
        }

        /**
         * Updates an existing review
         */
        public async updateReview(params: RequestType<typeof api_reviews_review_updateReview>): Promise<ResponseType<typeof api_reviews_review_updateReview>> {
            // Construct the body with only the fields which we want encoded within the body (excluding query string or header fields)
            const body: Record<string, any> = {
                cleanliness:    params.cleanliness,
                comment:        params.comment,
                communication:  params.communication,
                isAnonymous:    params.isAnonymous,
                isApproved:     params.isApproved,
                rating:         params.rating,
                serviceQuality: params.serviceQuality,
                waitTime:       params.waitTime,
                wouldRecommend: params.wouldRecommend,
            }

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/reviews/${encodeURIComponent(params.id)}`, {method: "PUT", body: JSON.stringify(body)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_reviews_review_updateReview>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { createCheckoutSession as api_stripe_checkout_createCheckoutSession } from "~backend/stripe/checkout";

export namespace stripe {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.createCheckoutSession = this.createCheckoutSession.bind(this)
        }

        /**
         * Creates a Stripe checkout session.
         */
        public async createCheckoutSession(params: RequestType<typeof api_stripe_checkout_createCheckoutSession>): Promise<ResponseType<typeof api_stripe_checkout_createCheckoutSession>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/stripe/checkout-session`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_stripe_checkout_createCheckoutSession>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import {
    adminCreateUser as api_supabase_auth_adminCreateUser,
    supabaseGetCurrentUser as api_supabase_auth_supabaseGetCurrentUser,
    supabaseLogin as api_supabase_auth_supabaseLogin,
    supabaseSignup as api_supabase_auth_supabaseSignup
} from "~backend/supabase/auth";

export namespace supabase {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.adminCreateUser = this.adminCreateUser.bind(this)
            this.supabaseGetCurrentUser = this.supabaseGetCurrentUser.bind(this)
            this.supabaseLogin = this.supabaseLogin.bind(this)
            this.supabaseSignup = this.supabaseSignup.bind(this)
        }

        /**
         * Creates a user from the admin dashboard.
         */
        public async adminCreateUser(params: RequestType<typeof api_supabase_auth_adminCreateUser>): Promise<ResponseType<typeof api_supabase_auth_adminCreateUser>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/supabase/auth/admin/create-user`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_supabase_auth_adminCreateUser>
        }

        /**
         * Get current user with Supabase
         */
        public async supabaseGetCurrentUser(): Promise<ResponseType<typeof api_supabase_auth_supabaseGetCurrentUser>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/supabase/auth/me`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_supabase_auth_supabaseGetCurrentUser>
        }

        /**
         * Login with Supabase
         */
        public async supabaseLogin(params: RequestType<typeof api_supabase_auth_supabaseLogin>): Promise<ResponseType<typeof api_supabase_auth_supabaseLogin>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/supabase/auth/login`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_supabase_auth_supabaseLogin>
        }

        /**
         * Signup with Supabase
         */
        public async supabaseSignup(params: RequestType<typeof api_supabase_auth_supabaseSignup>): Promise<ResponseType<typeof api_supabase_auth_supabaseSignup>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/supabase/auth/signup`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_supabase_auth_supabaseSignup>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import {
    createSession as api_telemedicine_session_createSession,
    deleteSession as api_telemedicine_session_deleteSession,
    getSession as api_telemedicine_session_getSession,
    joinSession as api_telemedicine_session_joinSession,
    listSessions as api_telemedicine_session_listSessions,
    updateSession as api_telemedicine_session_updateSession
} from "~backend/telemedicine/session";

export namespace telemedicine {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.createSession = this.createSession.bind(this)
            this.deleteSession = this.deleteSession.bind(this)
            this.getSession = this.getSession.bind(this)
            this.joinSession = this.joinSession.bind(this)
            this.listSessions = this.listSessions.bind(this)
            this.updateSession = this.updateSession.bind(this)
        }

        /**
         * Creates a new telemedicine session.
         */
        public async createSession(params: RequestType<typeof api_telemedicine_session_createSession>): Promise<ResponseType<typeof api_telemedicine_session_createSession>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/telemedicine/sessions`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_telemedicine_session_createSession>
        }

        /**
         * Deletes a telemedicine session.
         */
        public async deleteSession(params: { id: string }): Promise<void> {
            await this.baseClient.callTypedAPI(`/telemedicine/sessions/${encodeURIComponent(params.id)}`, {method: "DELETE", body: undefined})
        }

        /**
         * Retrieves a telemedicine session by ID.
         */
        public async getSession(params: { id: string }): Promise<ResponseType<typeof api_telemedicine_session_getSession>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/telemedicine/sessions/${encodeURIComponent(params.id)}`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_telemedicine_session_getSession>
        }

        /**
         * Joins a telemedicine session and returns connection details.
         */
        public async joinSession(params: { id: string }): Promise<ResponseType<typeof api_telemedicine_session_joinSession>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/telemedicine/sessions/${encodeURIComponent(params.id)}/join`, {method: "POST", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_telemedicine_session_joinSession>
        }

        /**
         * Lists telemedicine sessions with optional filtering.
         */
        public async listSessions(params: RequestType<typeof api_telemedicine_session_listSessions>): Promise<ResponseType<typeof api_telemedicine_session_listSessions>> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                doctorId:  params.doctorId,
                limit:     params.limit === undefined ? undefined : String(params.limit),
                offset:    params.offset === undefined ? undefined : String(params.offset),
                patientId: params.patientId,
                status:    params.status,
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/telemedicine/sessions`, {query, method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_telemedicine_session_listSessions>
        }

        /**
         * Updates an existing telemedicine session.
         */
        public async updateSession(params: RequestType<typeof api_telemedicine_session_updateSession>): Promise<ResponseType<typeof api_telemedicine_session_updateSession>> {
            // Construct the body with only the fields which we want encoded within the body (excluding query string or header fields)
            const body: Record<string, any> = {
                endTime:      params.endTime,
                notes:        params.notes,
                recordingUrl: params.recordingUrl,
                startTime:    params.startTime,
                status:       params.status,
            }

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/telemedicine/sessions/${encodeURIComponent(params.id)}`, {method: "PUT", body: JSON.stringify(body)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_telemedicine_session_updateSession>
        }
    }
}


type PickMethods<Type> = Omit<CallParameters, "method"> & { method?: Type };

// Helper type to omit all fields that are cookies.
type OmitCookie<T> = {
  [K in keyof T as T[K] extends CookieWithOptions<any> ? never : K]: T[K];
};

type RequestType<Type extends (...args: any[]) => any> =
  Parameters<Type> extends [infer H, ...any[]]
    ? OmitCookie<H>
    : void;

type ResponseType<Type extends (...args: any[]) => any> = OmitCookie<Awaited<ReturnType<Type>>>;

function dateReviver(key: string, value: any): any {
  if (
    typeof value === "string" &&
    value.length >= 10 &&
    value.charCodeAt(0) >= 48 && // '0'
    value.charCodeAt(0) <= 57 // '9'
  ) {
    const parsedDate = new Date(value);
    if (!isNaN(parsedDate.getTime())) {
      return parsedDate;
    }
  }
  return value;
}


function encodeQuery(parts: Record<string, string | string[]>): string {
    const pairs: string[] = []
    for (const key in parts) {
        const val = (Array.isArray(parts[key]) ?  parts[key] : [parts[key]]) as string[]
        for (const v of val) {
            pairs.push(`${key}=${encodeURIComponent(v)}`)
        }
    }
    return pairs.join("&")
}

// makeRecord takes a record and strips any undefined values from it,
// and returns the same record with a narrower type.
// @ts-ignore - TS ignore because makeRecord is not always used
function makeRecord<K extends string | number | symbol, V>(record: Record<K, V | undefined>): Record<K, V> {
    for (const key in record) {
        if (record[key] === undefined) {
            delete record[key]
        }
    }
    return record as Record<K, V>
}

import {
  StreamInOutHandlerFn,
  StreamInHandlerFn,
  StreamOutHandlerFn,
} from "encore.dev/api";

type StreamRequest<Type> = Type extends
  | StreamInOutHandlerFn<any, infer Req, any>
  | StreamInHandlerFn<any, infer Req, any>
  | StreamOutHandlerFn<any, any>
  ? Req
  : never;

type StreamResponse<Type> = Type extends
  | StreamInOutHandlerFn<any, any, infer Resp>
  | StreamInHandlerFn<any, any, infer Resp>
  | StreamOutHandlerFn<any, infer Resp>
  ? Resp
  : never;


function encodeWebSocketHeaders(headers: Record<string, string>) {
    // url safe, no pad
    const base64encoded = btoa(JSON.stringify(headers))
      .replaceAll("=", "")
      .replaceAll("+", "-")
      .replaceAll("/", "_");
    return "encore.dev.headers." + base64encoded;
}

class WebSocketConnection {
    public ws: WebSocket;

    private hasUpdateHandlers: (() => void)[] = [];

    constructor(url: string, headers?: Record<string, string>) {
        let protocols = ["encore-ws"];
        if (headers) {
            protocols.push(encodeWebSocketHeaders(headers))
        }

        this.ws = new WebSocket(url, protocols)

        this.on("error", () => {
            this.resolveHasUpdateHandlers();
        });

        this.on("close", () => {
            this.resolveHasUpdateHandlers();
        });
    }

    resolveHasUpdateHandlers() {
        const handlers = this.hasUpdateHandlers;
        this.hasUpdateHandlers = [];

        for (const handler of handlers) {
            handler()
        }
    }

    async hasUpdate() {
        // await until a new message have been received, or the socket is closed
        await new Promise((resolve) => {
            this.hasUpdateHandlers.push(() => resolve(null))
        });
    }

    on(type: "error" | "close" | "message" | "open", handler: (event: any) => void) {
        this.ws.addEventListener(type, handler);
    }

    off(type: "error" | "close" | "message" | "open", handler: (event: any) => void) {
        this.ws.removeEventListener(type, handler);
    }

    close() {
        this.ws.close();
    }
}

export class StreamInOut<Request, Response> {
    public socket: WebSocketConnection;
    private buffer: Response[] = [];

    constructor(url: string, headers?: Record<string, string>) {
        this.socket = new WebSocketConnection(url, headers);
        this.socket.on("message", (event: any) => {
            this.buffer.push(JSON.parse(event.data, dateReviver));
            this.socket.resolveHasUpdateHandlers();
        });
    }

    close() {
        this.socket.close();
    }

    async send(msg: Request) {
        if (this.socket.ws.readyState === WebSocket.CONNECTING) {
            // await that the socket is opened
            await new Promise((resolve) => {
                this.socket.ws.addEventListener("open", resolve, { once: true });
            });
        }

        return this.socket.ws.send(JSON.stringify(msg));
    }

    async next(): Promise<Response | undefined> {
        for await (const next of this) return next;
        return undefined;
    }

    async *[Symbol.asyncIterator](): AsyncGenerator<Response, undefined, void> {
        while (true) {
            if (this.buffer.length > 0) {
                yield this.buffer.shift() as Response;
            } else {
                if (this.socket.ws.readyState === WebSocket.CLOSED) return;
                await this.socket.hasUpdate();
            }
        }
    }
}

export class StreamIn<Response> {
    public socket: WebSocketConnection;
    private buffer: Response[] = [];

    constructor(url: string, headers?: Record<string, string>) {
        this.socket = new WebSocketConnection(url, headers);
        this.socket.on("message", (event: any) => {
            this.buffer.push(JSON.parse(event.data, dateReviver));
            this.socket.resolveHasUpdateHandlers();
        });
    }

    close() {
        this.socket.close();
    }

    async next(): Promise<Response | undefined> {
        for await (const next of this) return next;
        return undefined;
    }

    async *[Symbol.asyncIterator](): AsyncGenerator<Response, undefined, void> {
        while (true) {
            if (this.buffer.length > 0) {
                yield this.buffer.shift() as Response;
            } else {
                if (this.socket.ws.readyState === WebSocket.CLOSED) return;
                await this.socket.hasUpdate();
            }
        }
    }
}

export class StreamOut<Request, Response> {
    public socket: WebSocketConnection;
    private responseValue: Promise<Response>;

    constructor(url: string, headers?: Record<string, string>) {
        let responseResolver: (_: any) => void;
        this.responseValue = new Promise((resolve) => responseResolver = resolve);

        this.socket = new WebSocketConnection(url, headers);
        this.socket.on("message", (event: any) => {
            responseResolver(JSON.parse(event.data, dateReviver))
        });
    }

    async response(): Promise<Response> {
        return this.responseValue;
    }

    close() {
        this.socket.close();
    }

    async send(msg: Request) {
        if (this.socket.ws.readyState === WebSocket.CONNECTING) {
            // await that the socket is opened
            await new Promise((resolve) => {
                this.socket.ws.addEventListener("open", resolve, { once: true });
            });
        }

        return this.socket.ws.send(JSON.stringify(msg));
    }
}
// CallParameters is the type of the parameters to a method call, but require headers to be a Record type
type CallParameters = Omit<RequestInit, "headers"> & {
    /** Headers to be sent with the request */
    headers?: Record<string, string>

    /** Query parameters to be sent with the request */
    query?: Record<string, string | string[]>
}

// AuthDataGenerator is a function that returns a new instance of the authentication data required by this API
export type AuthDataGenerator = () =>
  | RequestType<typeof auth_supabaseAuth>
  | Promise<RequestType<typeof auth_supabaseAuth> | undefined>
  | undefined;

// A fetcher is the prototype for the inbuilt Fetch function
export type Fetcher = typeof fetch;

const boundFetch = fetch.bind(this);

class BaseClient {
    readonly baseURL: string
    readonly fetcher: Fetcher
    readonly headers: Record<string, string>
    readonly requestInit: Omit<RequestInit, "headers"> & { headers?: Record<string, string> }
    readonly authGenerator?: AuthDataGenerator

    constructor(baseURL: string, options: ClientOptions) {
        this.baseURL = baseURL
        this.headers = {}

        // Add User-Agent header if the script is running in the server
        // because browsers do not allow setting User-Agent headers to requests
        if (!BROWSER) {
            this.headers["User-Agent"] = "-Generated-TS-Client (Encore/1.48.13)";
        }

        this.requestInit = options.requestInit ?? {};

        // Setup what fetch function we'll be using in the base client
        if (options.fetcher !== undefined) {
            this.fetcher = options.fetcher
        } else {
            this.fetcher = boundFetch
        }

        // Setup an authentication data generator using the auth data token option
        if (options.auth !== undefined) {
            const auth = options.auth
            if (typeof auth === "function") {
                this.authGenerator = auth
            } else {
                this.authGenerator = () => auth
            }
        }
    }

    async getAuthData(): Promise<CallParameters | undefined> {
        let authData: RequestType<typeof auth_supabaseAuth> | undefined;

        // If authorization data generator is present, call it and add the returned data to the request
        if (this.authGenerator) {
            const mayBePromise = this.authGenerator();
            if (mayBePromise instanceof Promise) {
                authData = await mayBePromise;
            } else {
                authData = mayBePromise;
            }
        }

        if (authData) {
            const data: CallParameters = {};

            data.headers = makeRecord<string, string>({
                authorization: authData.authorization,
            });

            return data;
        }

        return undefined;
    }

    // createStreamInOut sets up a stream to a streaming API endpoint.
    async createStreamInOut<Request, Response>(path: string, params?: CallParameters): Promise<StreamInOut<Request, Response>> {
        let { query, headers } = params ?? {};

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                headers = {...headers, ...authData.headers};
            }
        }

        const queryString = query ? '?' + encodeQuery(query) : ''
        return new StreamInOut(this.baseURL + path + queryString, headers);
    }

    // createStreamIn sets up a stream to a streaming API endpoint.
    async createStreamIn<Response>(path: string, params?: CallParameters): Promise<StreamIn<Response>> {
        let { query, headers } = params ?? {};

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                headers = {...headers, ...authData.headers};
            }
        }

        const queryString = query ? '?' + encodeQuery(query) : ''
        return new StreamIn(this.baseURL + path + queryString, headers);
    }

    // createStreamOut sets up a stream to a streaming API endpoint.
    async createStreamOut<Request, Response>(path: string, params?: CallParameters): Promise<StreamOut<Request, Response>> {
        let { query, headers } = params ?? {};

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                headers = {...headers, ...authData.headers};
            }
        }

        const queryString = query ? '?' + encodeQuery(query) : ''
        return new StreamOut(this.baseURL + path + queryString, headers);
    }

    // callTypedAPI makes an API call, defaulting content type to "application/json"
    public async callTypedAPI(path: string, params?: CallParameters): Promise<Response> {
        return this.callAPI(path, {
            ...params,
            headers: { "Content-Type": "application/json", ...params?.headers }
        });
    }

    // callAPI is used by each generated API method to actually make the request
    public async callAPI(path: string, params?: CallParameters): Promise<Response> {
        let { query, headers, ...rest } = params ?? {}
        const init = {
            ...this.requestInit,
            ...rest,
        }

        // Merge our headers with any predefined headers
        init.headers = {...this.headers, ...init.headers, ...headers}

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                init.headers = {...init.headers, ...authData.headers};
            }
        }

        // Make the actual request
        const queryString = query ? '?' + encodeQuery(query) : ''
        const response = await this.fetcher(this.baseURL+path+queryString, init)

        // handle any error responses
        if (!response.ok) {
            // try and get the error message from the response body
            let body: APIErrorResponse = { code: ErrCode.Unknown, message: `request failed: status ${response.status}` }

            // if we can get the structured error we should, otherwise give a best effort
            try {
                const text = await response.text()

                try {
                    const jsonBody = JSON.parse(text)
                    if (isAPIErrorResponse(jsonBody)) {
                        body = jsonBody
                    } else {
                        body.message += ": " + JSON.stringify(jsonBody)
                    }
                } catch {
                    body.message += ": " + text
                }
            } catch (e) {
                // otherwise we just append the text to the error message
                body.message += ": " + String(e)
            }

            throw new APIError(response.status, body)
        }

        return response
    }
}

/**
 * APIErrorDetails represents the response from an Encore API in the case of an error
 */
interface APIErrorResponse {
    code: ErrCode
    message: string
    details?: any
}

function isAPIErrorResponse(err: any): err is APIErrorResponse {
    return (
        err !== undefined && err !== null &&
        isErrCode(err.code) &&
        typeof(err.message) === "string" &&
        (err.details === undefined || err.details === null || typeof(err.details) === "object")
    )
}

function isErrCode(code: any): code is ErrCode {
    return code !== undefined && Object.values(ErrCode).includes(code)
}

/**
 * APIError represents a structured error as returned from an Encore application.
 */
export class APIError extends Error {
    /**
     * The HTTP status code associated with the error.
     */
    public readonly status: number

    /**
     * The Encore error code
     */
    public readonly code: ErrCode

    /**
     * The error details
     */
    public readonly details?: any

    constructor(status: number, response: APIErrorResponse) {
        // extending errors causes issues after you construct them, unless you apply the following fixes
        super(response.message);

        // set error name as constructor name, make it not enumerable to keep native Error behavior
        // https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/new.target#new.target_in_constructors
        Object.defineProperty(this, 'name', {
            value:        'APIError',
            enumerable:   false,
            configurable: true,
        })

        // fix the prototype chain
        if ((Object as any).setPrototypeOf == undefined) {
            (this as any).__proto__ = APIError.prototype
        } else {
            Object.setPrototypeOf(this, APIError.prototype);
        }

        // capture a stack trace
        if ((Error as any).captureStackTrace !== undefined) {
            (Error as any).captureStackTrace(this, this.constructor);
        }

        this.status = status
        this.code = response.code
        this.details = response.details
    }
}

/**
 * Typeguard allowing use of an APIError's fields'
 */
export function isAPIError(err: any): err is APIError {
    return err instanceof APIError;
}

export enum ErrCode {
    /**
     * OK indicates the operation was successful.
     */
    OK = "ok",

    /**
     * Canceled indicates the operation was canceled (typically by the caller).
     *
     * Encore will generate this error code when cancellation is requested.
     */
    Canceled = "canceled",

    /**
     * Unknown error. An example of where this error may be returned is
     * if a Status value received from another address space belongs to
     * an error-space that is not known in this address space. Also
     * errors raised by APIs that do not return enough error information
     * may be converted to this error.
     *
     * Encore will generate this error code in the above two mentioned cases.
     */
    Unknown = "unknown",

    /**
     * InvalidArgument indicates client specified an invalid argument.
     * Note that this differs from FailedPrecondition. It indicates arguments
     * that are problematic regardless of the state of the system
     * (e.g., a malformed file name).
     *
     * This error code will not be generated by the gRPC framework.
     */
    InvalidArgument = "invalid_argument",

    /**
     * DeadlineExceeded means operation expired before completion.
     * For operations that change the state of the system, this error may be
     * returned even if the operation has completed successfully. For
     * example, a successful response from a server could have been delayed
     * long enough for the deadline to expire.
     *
     * The gRPC framework will generate this error code when the deadline is
     * exceeded.
     */
    DeadlineExceeded = "deadline_exceeded",

    /**
     * NotFound means some requested entity (e.g., file or directory) was
     * not found.
     *
     * This error code will not be generated by the gRPC framework.
     */
    NotFound = "not_found",

    /**
     * AlreadyExists means an attempt to create an entity failed because one
     * already exists.
     *
     * This error code will not be generated by the gRPC framework.
     */
    AlreadyExists = "already_exists",

    /**
     * PermissionDenied indicates the caller does not have permission to
     * execute the specified operation. It must not be used for rejections
     * caused by exhausting some resource (use ResourceExhausted
     * instead for those errors). It must not be
     * used if the caller cannot be identified (use Unauthenticated
     * instead for those errors).
     *
     * This error code will not be generated by the gRPC core framework,
     * but expect authentication middleware to use it.
     */
    PermissionDenied = "permission_denied",

    /**
     * ResourceExhausted indicates some resource has been exhausted, perhaps
     * a per-user quota, or perhaps the entire file system is out of space.
     *
     * This error code will be generated by the gRPC framework in
     * out-of-memory and server overload situations, or when a message is
     * larger than the configured maximum size.
     */
    ResourceExhausted = "resource_exhausted",

    /**
     * FailedPrecondition indicates operation was rejected because the
     * system is not in a state required for the operation's execution.
     * For example, directory to be deleted may be non-empty, an rmdir
     * operation is applied to a non-directory, etc.
     *
     * A litmus test that may help a service implementor in deciding
     * between FailedPrecondition, Aborted, and Unavailable:
     *  (a) Use Unavailable if the client can retry just the failing call.
     *  (b) Use Aborted if the client should retry at a higher-level
     *      (e.g., restarting a read-modify-write sequence).
     *  (c) Use FailedPrecondition if the client should not retry until
     *      the system state has been explicitly fixed. E.g., if an "rmdir"
     *      fails because the directory is non-empty, FailedPrecondition
     *      should be returned since the client should not retry unless
     *      they have first fixed up the directory by deleting files from it.
     *  (d) Use FailedPrecondition if the client performs conditional
     *      REST Get/Update/Delete on a resource and the resource on the
     *      server does not match the condition. E.g., conflicting
     *      read-modify-write on the same resource.
     *
     * This error code will not be generated by the gRPC framework.
     */
    FailedPrecondition = "failed_precondition",

    /**
     * Aborted indicates the operation was aborted, typically due to a
     * concurrency issue like sequencer check failures, transaction aborts,
     * etc.
     *
     * See litmus test above for deciding between FailedPrecondition,
     * Aborted, and Unavailable.
     */
    Aborted = "aborted",

    /**
     * OutOfRange means operation was attempted past the valid range.
     * E.g., seeking or reading past end of file.
     *
     * Unlike InvalidArgument, this error indicates a problem that may
     * be fixed if the system state changes. For example, a 32-bit file
     * system will generate InvalidArgument if asked to read at an
     * offset that is not in the range [0,2^32-1], but it will generate
     * OutOfRange if asked to read from an offset past the current
     * file size.
     *
     * There is a fair bit of overlap between FailedPrecondition and
     * OutOfRange. We recommend using OutOfRange (the more specific
     * error) when it applies so that callers who are iterating through
     * a space can easily look for an OutOfRange error to detect when
     * they are done.
     *
     * This error code will not be generated by the gRPC framework.
     */
    OutOfRange = "out_of_range",

    /**
     * Unimplemented indicates operation is not implemented or not
     * supported/enabled in this service.
     *
     * This error code will be generated by the gRPC framework. Most
     * commonly, you will see this error code when a method implementation
     * is missing on the server. It can also be generated for unknown
     * compression algorithms or a disagreement as to whether an RPC should
     * be streaming.
     */
    Unimplemented = "unimplemented",

    /**
     * Internal errors. Means some invariants expected by underlying
     * system has been broken. If you see one of these errors,
     * something is very broken.
     *
     * This error code will be generated by the gRPC framework in several
     * internal error conditions.
     */
    Internal = "internal",

    /**
     * Unavailable indicates the service is currently unavailable.
     * This is a most likely a transient condition and may be corrected
     * by retrying with a backoff. Note that it is not always safe to retry
     * non-idempotent operations.
     *
     * See litmus test above for deciding between FailedPrecondition,
     * Aborted, and Unavailable.
     *
     * This error code will be generated by the gRPC framework during
     * abrupt shutdown of a server process or network connection.
     */
    Unavailable = "unavailable",

    /**
     * DataLoss indicates unrecoverable data loss or corruption.
     *
     * This error code will not be generated by the gRPC framework.
     */
    DataLoss = "data_loss",

    /**
     * Unauthenticated indicates the request does not have valid
     * authentication credentials for the operation.
     *
     * The gRPC framework will generate this error code when the
     * authentication metadata is invalid or a Credentials callback fails,
     * but also expect authentication middleware to generate it.
     */
    Unauthenticated = "unauthenticated",
}

export default new Client(import.meta.env.VITE_CLIENT_TARGET, { requestInit: { credentials: "include" } });
